on:
  pull_request:
    branches:
      - production
    paths-ignore:
      - '**.md'
      - '**.*ignore'
      - renovate.json
      - '**deployment.yaml'

jobs:
  integration:
    name: Check branch integration
    runs-on: ubuntu-22.04
    permissions: read-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: production

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type-check affected projects
        run: pnpm affected:typecheck

      - name: Build affected projects
        run: pnpm affected:build
